---
- name: Common setup for all instances
  hosts: all
  become: yes
  roles:
    - common
    - docker

- name: Deploy Redis service
  hosts: redis
  become: yes
  roles:
    - redis

- name: Deploy PostgreSQL database
  hosts: postgres
  become: yes
  roles:
    - postgres

- name: Deploy Worker backend
  hosts: worker
  become: yes
  roles:
    - worker

- name: Deploy Vote frontend
  hosts: vote
  become: yes
  roles:
    - vote

- name: Deploy Result frontend
  hosts: result
  become: yes
  roles:
    - result
