- name: Include common host injection
  import_role:
    name: common
    tasks_from: inject_hosts.yml

- name: Wait for Redis from worker host
  ansible.builtin.wait_for:
    host: redis
    port: 6379
    timeout: 60
  delegate_to: "{{ inventory_hostname }}"
  register: redis_ready

- name: Wait for Postgres from worker host
  ansible.builtin.wait_for:
    host: postgres
    port: 5432
    timeout: 60
  delegate_to: "{{ inventory_hostname }}"
  register: postgres_ready

- name: Pull Worker Image
  community.docker.docker_image:
    name: sunilzishan/worker
    source: pull
    tag: latest
  when: redis_ready.succeeded and postgres_ready.succeeded

- name: Run Worker Container
  community.docker.docker_container:
    name: worker
    image: sunilzishan/worker:latest
    env:
      DB_HOST: "{{ hostvars['postgres']['ansible_host'] }}"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      REDIS_HOST: "{{ hostvars['redis']['ansible_host'] }}"
    state: started
    restart_policy: always
  when: redis_ready.succeeded and postgres_ready.succeeded

- name: Log failure if dependencies are not ready
  ansible.builtin.debug:
    msg: "Worker container not started because Redis or Postgres is not ready."
  when: redis_ready.failed or postgres_ready.failed
