- name: Wait for Redis
  wait_for:
    host: redis
    port: 6379
    timeout: 60

- name: Wait for Postgres
  wait_for:
    host: postgres
    port: 5432
    timeout: 60

- name: Pull Worker Image
  community.docker.docker_image:
    name: sunilzishan/worker
    source: pull
    tag: latest

- name: Run Worker Container
  community.docker.docker_container:
    name: worker
    image: sunilzishan/worker:latest
    env:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      REDIS_HOST: redis
    state: started
    restart_policy: always
